project:
  envCcd: D
logging:
  pattern:
    console: "%white([%d{yyyy-MM-dd HH:mm:ss}]) %yellow([%thread]) %highlight([%-5level]) %white([%-35logger{35}]) %white(%msg  %n)"
  level:
    root: WARN
    com.shinhancard: DEBUG
    jpa: DEBUG
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      #http://localhost:8080/h2-console/login.do?jsessionid=3d2ba6a6097c98c79297ff2547145cbd
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
